version: '3.3'
services:
    adguardhome:
        container_name: adguardhome
        restart: unless-stopped
        volumes:
            - 'C:\Users\ARIA\Docker\AdGuard-Home\data:/opt/adguardhome/work'
            - 'C:\Users\ARIA\Docker\AdGuard-Home\config:/opt/adguardhome/conf'
        ports:
            - '53:53/tcp'
            - '53:53/udp'
            - '80:80/tcp'
            - '443:443/tcp'
            - '443:443/udp'
            - '3000:3000/tcp'
        image: adguard/adguardhome:latest